export const countryOptions = [
  { title: 'Україна', value: 'Ukraine' },
  { title: 'Польща', value: 'Poland' },
  { title: 'Німеччина', value: 'Germany' },
  { title: 'Франція', value: 'France' },
  { title: 'США', value: 'USA' },
  { title: 'Канада', value: 'Canada' },
  { title: 'Велика Британія', value: 'United Kingdom' },
  { title: 'Іспанія', value: 'Spain' },
  { title: 'Італія', value: 'Italy' },
  { title: 'Нідерланди', value: 'Netherlands' },
  { title: 'Швеція', value: 'Sweden' },
  { title: 'Норвегія', value: 'Norway' },
  { title: 'Фінляндія', value: 'Finland' },
  { title: 'Данія', value: 'Denmark' },
  { title: 'Чехія', value: 'Czech Republic' },
  { title: 'Австрія', value: 'Austria' },
  { title: 'Швейцарія', value: 'Switzerland' },
  { title: 'Бельгія', value: 'Belgium' },
  { title: 'Португалія', value: 'Portugal' },
  { title: 'Румунія', value: 'Romania' },
  { title: 'Угорщина', value: 'Hungary' },
  { title: 'Словаччина', value: 'Slovakia' },
  { title: 'Болгарія', value: 'Bulgaria' },
  { title: 'Греція', value: 'Greece' },
  { title: 'Туреччина', value: 'Turkey' },
  { title: 'Естонія', value: 'Estonia' },
  { title: 'Латвія', value: 'Latvia' },
  { title: 'Литва', value: 'Lithuania' },
  { title: 'Ірландія', value: 'Ireland' },
  { title: 'Хорватія', value: 'Croatia' },
  { title: 'Сербія', value: 'Serbia' },
  { title: 'Словенія', value: 'Slovenia' },
  { title: 'Люксембург', value: 'Luxembourg' },
  { title: 'Ісландія', value: 'Iceland' },
  { title: 'Мальта', value: 'Malta' },
  { title: 'Кіпр', value: 'Cyprus' },
  { title: 'Молдова', value: 'Moldova' },
  { title: 'Грузія', value: 'Georgia' },
  { title: 'Вірменія', value: 'Armenia' },
  { title: 'Азербайджан', value: 'Azerbaijan' },
  { title: 'Казахстан', value: 'Kazakhstan' },
  { title: 'Узбекистан', value: 'Uzbekistan' },
  { title: 'Білорусь', value: 'Belarus' },
  { title: 'Росія', value: 'Russia' },
  { title: 'Китай', value: 'China' },
  { title: 'Японія', value: 'Japan' },
  { title: 'Південна Корея', value: 'South Korea' },
  { title: 'Індія', value: 'India' },
  { title: 'Австралія', value: 'Australia' },
  { title: 'Нова Зеландія', value: 'New Zealand' },
  { title: 'Бразилія', value: 'Brazil' },
  { title: 'Аргентина', value: 'Argentina' },
  { title: 'Мексика', value: 'Mexico' },
  { title: 'Чилі', value: 'Chile' },
  { title: 'Колумбія', value: 'Colombia' },
  { title: 'ПАР', value: 'South Africa' },
  { title: 'Єгипет', value: 'Egypt' },
  { title: 'Ізраїль', value: 'Israel' },
  { title: 'Саудівська Аравія', value: 'Saudi Arabia' },
  { title: 'ОАЕ', value: 'UAE' },
  { title: 'Катар', value: 'Qatar' },
  { title: 'Сінгапур', value: 'Singapore' },
  { title: 'Таїланд', value: 'Thailand' },
  { title: 'Вʼєтнам', value: 'Vietnam' },
  { title: 'Малайзія', value: 'Malaysia' },
  { title: 'Індонезія', value: 'Indonesia' },
  { title: 'Філіппіни', value: 'Philippines' },
  { title: 'Пакистан', value: 'Pakistan' },
  { title: 'Бангладеш', value: 'Bangladesh' },
  { title: 'Нігерія', value: 'Nigeria' },
  { title: 'Кенія', value: 'Kenya' },
  { title: 'Марокко', value: 'Morocco' },
  { title: 'Алжир', value: 'Algeria' },
  { title: 'Туніс', value: 'Tunisia' },
  { title: 'Лівія', value: 'Libya' },
  { title: 'Судан', value: 'Sudan' },
  { title: 'Ефіопія', value: 'Ethiopia' },
  { title: 'Гана', value: 'Ghana' },
  { title: 'Кот-дʼІвуар', value: 'Ivory Coast' },
  { title: 'Камерун', value: 'Cameroon' },
  { title: 'Сенегал', value: 'Senegal' },
  { title: 'Ангола', value: 'Angola' },
  { title: 'Мозамбік', value: 'Mozambique' },
  { title: 'Танзанія', value: 'Tanzania' },
  { title: 'Уганда', value: 'Uganda' },
  { title: 'Замбія', value: 'Zambia' },
  { title: 'Зімбабве', value: 'Zimbabwe' },
  { title: 'Ботсвана', value: 'Botswana' },
  { title: 'Намібія', value: 'Namibia' },
  { title: 'Мадагаскар', value: 'Madagascar' },
  { title: 'Маврикій', value: 'Mauritius' },
  { title: 'Сейшели', value: 'Seychelles' },
  { title: 'Малаві', value: 'Malawi' },
  { title: 'Руанда', value: 'Rwanda' },
  { title: 'Бурунді', value: 'Burundi' },
  { title: 'Сомалі', value: 'Somalia' },
  { title: 'Конго', value: 'Congo' },
  { title: 'Габон', value: 'Gabon' },
  { title: 'Екваторіальна Гвінея', value: 'Equatorial Guinea' },
  { title: 'Гвінея', value: 'Guinea' },
  { title: 'Сьєрра-Леоне', value: 'Sierra Leone' },
  { title: 'Ліберія', value: 'Liberia' },
  { title: 'Того', value: 'Togo' },
  { title: 'Бенін', value: 'Benin' },
  { title: 'Буркіна-Фасо', value: 'Burkina Faso' },
  { title: 'Нігер', value: 'Niger' },
  { title: 'Чад', value: 'Chad' },
  { title: 'ЦАР', value: 'Central African Republic' },
  { title: 'Південний Судан', value: 'South Sudan' },
  { title: 'Еритрея', value: 'Eritrea' },
  { title: 'Джибуті', value: 'Djibouti' },
  { title: 'Коморські Острови', value: 'Comoros' },
  { title: 'Сан-Томе і Принсіпі', value: 'Sao Tome and Principe' },
  { title: 'Кабо-Верде', value: 'Cape Verde' },
  { title: 'Гамбія', value: 'Gambia' },
  { title: 'Гвінея-Бісау', value: 'Guinea-Bissau' },
  { title: 'Лесото', value: 'Lesotho' },
  { title: 'Свазіленд', value: 'Swaziland' },
  { title: 'Західна Сахара', value: 'Western Sahara' }
]; 