namespace: production

replicaCount: 1

image:
  repository: ""
  pullPolicy: IfNotPresent
  tag: ""

imagePullSecrets:
  - name: "do-registry"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: false
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "80"
  name: ""

podAnnotations: {}
podLabels: {}

podSecurityContext: {}

securityContext: {}

service:
  create: true
  type: ClusterIP
  port: 3000
  annotations: {}

ingress:
  enabled: false
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
  hosts:
    - host: haxfe.fewcats.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - haxfe.fewcats.com
      secretName: haxfe-tls

resources:
  limits:
    cpu: 2000m
    memory: 4096Mi
  requests:
    cpu: 50m
    memory: 128Mi

livenessProbe:
  httpGet:
    path: /health
    port: 3000
readinessProbe:
  httpGet:
    path: /health
    port: 3000

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 2000
  targetMemoryUtilizationPercentage: 2000

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}

envFrom:
  - configMapRef:
      name: tma-front-configmap
